[project]
name = "additive-manufacturing-agent"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "additive-manufacturing>=0.0.1",
]

